apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: {{ include "custom-app.fullname" . }}
    labels:
        {{- include "custom-app.labels" . | nindent 4 }}
data:
    .dockerconfigjson: {{ .Values.dockerconfigsecret | b64enc }}